# List of available google docs URL 

# until i find a way to programmatically generate new google docs, i will use this
glist = [
'https://docs.google.com/document/d/1QTvDx4NaaGugjwWB-TgceNAZsE9Re1wEyY4wY0Bd1cw/edit?usp=sharing',
'https://docs.google.com/document/d/1igFNUwj3bbyp-mPX9GcAQfUwG5AuXm71X9jKCtn52A0/edit?usp=sharing',
'https://docs.google.com/document/d/12JoPsP3xGAS4qR22KIiDH5__rXXHgl_4HoCGnF8PZJE/edit?usp=sharing',
'https://docs.google.com/document/d/1bpPLGDO_go3tFMd9Jsuyl3wm8o0MhuoRmDKMkqohNzE/edit?usp=sharing',
'https://docs.google.com/document/d/1QjbM0grrY-RulEKTZKzDRddx2DcWfj9VdmZPNyvsgew/edit?usp=sharing',
'https://docs.google.com/document/d/1md2CYh3MJc2t7R04txr1s0-UtAgQ1sHJFfn6Tb_U_Uk/edit?usp=sharing',
'https://docs.google.com/document/d/1dVS5qwO9wt3Dbxotds6XeVeCXCAfJf0BGZ2jcaRYUac/edit?usp=sharing',
'https://docs.google.com/document/d/1t6374TipgRDbho6jNwesopRNZ20qXvdeZGImjAGeEdE/edit?usp=sharing',
'https://docs.google.com/document/d/1bdw36Cisdvv4zMEDpzmVb8hnxcWsrbQ4fjBtl5FRmwE/edit?usp=sharing',
'https://docs.google.com/document/d/1CffT_Z3OB3cdAg4qwCpVB-hpi5quri-pFpG0gJF7XDM/edit?usp=sharing',
'https://docs.google.com/document/d/1szN0BF7ePwxiEssKMMiC5hF_D9VL2wALPERHsgMbNzE/edit?usp=sharing',
'https://docs.google.com/document/d/1BZV06N8i1LAzkJRQVtX8eMmNnGmOpSKua5-7wR4NDi0/edit?usp=sharing',
'https://docs.google.com/document/d/1F4y3R_pl0fsp9cQg5XeGHGjXv3EVC0lLuY0k-F4CJ_E/edit?usp=sharing',
'https://docs.google.com/document/d/19WgIMXcSDP0tLLRtEvoFP1NMPl4KkcsaNVO6n52wEyw/edit?usp=sharing',
'https://docs.google.com/document/d/1g_OxJWERXKhHdLGzKmi4og9krTSpT5YWBxXfUCTdnVw/edit?usp=sharing',
'https://docs.google.com/document/d/1qm_zFn0ld747SHV_vcd4pJ7EnMDvrWDvAMO-W8OIkG8/edit?usp=sharing',
'https://docs.google.com/document/d/1V0fxkZAt7Uh2ygkJMEJIO-JmePmmUhgoLeYiP5vxXaI/edit?usp=sharing',
'https://docs.google.com/document/d/1rBiB4H-hrqlyu5NyTYKMHAJPT2CJJyeYagjyc9dVg0E/edit?usp=sharing',
'https://docs.google.com/document/d/17-tGxZeTS2QTUmTV0lxE4M3yV8bC1xUGdHS45bFA5p0/edit?usp=sharing',
'https://docs.google.com/document/d/1pizGqYPTZ-xc03wlP8bDtlYPdXt-42LiLCpuHaZkpEg/edit?usp=sharing',
'https://docs.google.com/document/d/1p4sv8_VNXUdA2P_ODESi_hZB07xgFcTF8yb-nflsTFg/edit?usp=sharing',
'https://docs.google.com/document/d/1x4Ht_-jjElx9UnekWph4WjZJSuoLhF2vNK2Fh8DD2bA/edit?usp=sharing',
'https://docs.google.com/document/d/1kBZBOPhMqks_RCTyPxCyFfky4yUl2jnYnzWhtCMbus4/edit?usp=sharing',
'https://docs.google.com/document/d/11yZEP81uskw7H4rkHms4Lbx5o0JqnS2NB0zb9Qt8kNY/edit?usp=sharing',
'https://docs.google.com/document/d/1s9VakvTyx70Wz_35SHUUHm7j6TnByismNo7AW_pW2ZE/edit?usp=sharing',
'https://docs.google.com/document/d/1J9qDATpqdycm5JbgCl8A4EryrzB48JkKqFrXZlwhHMk/edit?usp=sharing',
'https://docs.google.com/document/d/1l5_7k3oLzyI9tJCmG_nnxFVck4erq2Oerxd5bFwyjv4/edit?usp=sharing',
'https://docs.google.com/document/d/1zkMU1R8GO7Tr8brgONX-SITEhDgNIdkTyVvVCGh6qSc/edit?usp=sharing',
'https://docs.google.com/document/d/1SJSkLDJdpHHMDMx3Pi5UAzjZhlGwUwREC5PR2VUd1iU/edit?usp=sharing',
'https://docs.google.com/document/d/1U2Pi_DP1Pc22iQK2d9oy6w6o35D1TX1cFI6bHe_jqrU/edit?usp=sharing',
'https://docs.google.com/document/d/1YU8p4uTQDgpdJip_lk1V6Zcoe4nCuN2ja2tGh0ivBg0/edit?usp=sharing',
'https://docs.google.com/document/d/12vIMkw2I5QN1yHH10jit4sX9pnao09hz-ILOsqvE8iQ/edit?usp=sharing',
]